openapi: 3.0.0
info:
  title: Service Platform API
  version: 1.0.0
  description: API documentation for admin, partner, inquiry, review, and authentication modules.

servers:
  - url: http://localhost:5000/api

paths:
  /auth/signup:
    post:
      summary: Sign up
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successfully signed up

  /auth/login:
    post:
      summary: Login
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successfully logged in

  /admin/stats:
    get:
      summary: Admin dashboard stats
      tags: [Admin]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Admin stats

  /admin/partners/pending:
    get:
      summary: Get pending partner requests
      tags: [Admin]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of pending partners

  /admin/partners/{id}/status:
    put:
      summary: Verify partner
      tags: [Admin]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Partner verified

  /admin/categories:
    get:
      summary: Get all categories
      tags: [Admin]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of categories

    post:
      summary: Create category
      tags: [Admin]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '201':
          description: Category created

  /partner/onboard:
    post:
      summary: Submit partner details
      tags: [Partner]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Partner details submitted

  /inquiries/submit:
    post:
      summary: Client submits inquiry
      tags: [Inquiry]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Inquiry submitted

  /inquiries/assigned:
    get:
      summary: Partner gets assigned inquiries
      tags: [Inquiry]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of assigned inquiries

  /reviews:
    get:
      summary: Get all reviews (admin)
      tags: [Review]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of reviews

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT